import { AiOutlineUser } from "react-icons/ai";
import { BiGlobe, BiUserCheck } from "react-icons/bi";
import { CiCalendar, CiPower } from "react-icons/ci";
import { GoArrowDownLeft, GoArrowUpRight } from "react-icons/go";
import { MdOutlineMailOutline } from "react-icons/md";
import {
  PiDevices,
  PiPlugsConnected,
  PiTimerThin,
  PiUploadLight,
  PiUsersThree,
} from "react-icons/pi";
import { TbPlugConnected } from "react-icons/tb";

export const data = [
  {
    name: "Page A",
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Page B",
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: "Page C",
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: "Page D",
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "Page E",
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "Page F",
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "Page G",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
];

export const cloudNetworkData = [
  {
    id: 1,
    icon: <AiOutlineUser />,
    title: "Users",
    number: 3836,
    percentage: 15,
    text: "Compared to last month",
    direction: "down",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
      {
        name: "Page D",
        uv: 2780,
        pv: 3908,
        amt: 2000,
      },
      {
        name: "Page E",
        uv: 1890,
        pv: 4800,
        amt: 2181,
      },
    ],
  },
  {
    id: 2,
    icon: <PiUsersThree />,
    title: "Groups",
    number: 316,
    percentage: 23,
    text: "Compared to last month",
    direction: "down",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
    ],
  },
  {
    id: 3,
    icon: <PiUploadLight />,
    title: "Upload",
    number: 316,
    percentage: 2,
    text: "Compared to last month",
    direction: "up",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
    ],
  },
  {
    id: 4,
    icon: <AiOutlineUser />,
    title: "Bounce Rate",
    number: 50,
    percentage: 5,
    text: "Compared to last month",
    direction: "up",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
    ],
  },
];
export const deviceMgtDataSide = [
  {
    id: 1,
    icon: <AiOutlineUser />,
    title: "Users",
    number: 3836,
    percentage: 15,
    text: "Compared to last month",
    direction: "down",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
      {
        name: "Page D",
        uv: 2780,
        pv: 3908,
        amt: 2000,
      },
      {
        name: "Page E",
        uv: 1890,
        pv: 4800,
        amt: 2181,
      },
    ],
  },
  {
    id: 2,
    icon: <PiUsersThree />,
    title: "Groups",
    number: 316,
    percentage: 23,
    text: "Compared to last month",
    direction: "down",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
    ],
  },
];
export const deviceMgtData = [
  {
    id: 1,
    icon: <PiDevices />,
    title: "Number Of Devices",
    number: 3836,
    percentage: 15,
    text: "Compared to last month",
    direction: "up",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
      {
        name: "Page D",
        uv: 2780,
        pv: 3908,
        amt: 2000,
      },
      {
        name: "Page E",
        uv: 1890,
        pv: 4800,
        amt: 2181,
      },
    ],
    deviceIcon1: <PiPlugsConnected />,
    deviceText1: "Plugged",
    deviceNumber1: 1923,
    deviceIcon2: <TbPlugConnected />,
    deviceText2: "Unplugged",
    deviceNumber2: 1913,
    cardData: [
      {
        icon: <PiPlugsConnected />,
        name: "Plugged",
        number: 1923,
        text: "Devices",
      },
      {
        icon: <TbPlugConnected />,
        name: "Unplugged",
        number: 1913,
        text: "Devices",
      },
      {
        icon: <PiPlugsConnected />,
        name: "Plugged",
        number: 1923,
        text: "Devices",
      },
    ],
  },
  {
    id: 2,
    icon: <AiOutlineUser />,
    title: "Users",
    number: 3836,
    percentage: 15,
    text: "Compared to last month",
    direction: "down",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
    ],
    deviceIcon1: <CiPower />,
    deviceText1: "Active",
    deviceNumber1: 592,
    deviceIcon2: <AiOutlineUser />,
    deviceText2: "Offline",
    deviceNumber2: 3836,
    cardData: [
      {
        icon: <CiPower />,
        name: "Active",
        number: 592,
        text: "Devices",
      },
      {
        icon: <CiPower />,
        name: "Active",
        number: 592,
        text: "Devices",
      },
      {
        icon: <CiPower />,
        name: "Active",
        number: 592,
        text: "Devices",
      },
    ],
  },
  {
    id: 3,
    icon: <MdOutlineMailOutline />,
    title: "Emails",
    number: 316,
    percentage: 23,
    text: "Compared to last month",
    direction: "down",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
    ],
    deviceIcon1: <GoArrowUpRight />,
    deviceText1: "Sent",
    deviceNumber1: 592,
    deviceIcon2: <GoArrowDownLeft />,
    deviceText2: "Received",
    deviceNumber2: 3836,
    cardData: [
      {
        icon: <GoArrowUpRight />,
        name: "Sent",
        number: 592,
        text: "Emails",
      },
      {
        icon: <GoArrowDownLeft />,
        name: "Received",
        number: 3836,
        text: "Emails",
      },
    ],
  },
];

export const deviceData = [{}];

const countryData = [
  {
    name: "United States",
    number: 75,
    img: "/usa.jpeg",
  },
  {
    name: "United Kingdom",
    number: 50,
    img: "/uk.png",
  },
  {
    name: "Nigeria",
    number: 25,
    img: "/nig.png",
  },
  {
    name: "UAE",
    number: 10,
    img: "/uae.png",
  },
  {
    name: "Canada",
    number: 10,
    img: "/canada.png",
  },
];

export { countryData };

export const productivityData = [
  {
    id: 1,
    icon: <PiTimerThin />,
    title: "Hours of Productivity",
    number: 576,
    subtext: "hrs",
    percentage: 15,
    text: "Compared to last month",
    direction: "down",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
      {
        name: "Page D",
        uv: 2780,
        pv: 3908,
        amt: 2000,
      },
      {
        name: "Page E",
        uv: 1890,
        pv: 4800,
        amt: 2181,
      },
    ],
  },
  {
    id: 2,
    icon: <CiCalendar />,
    title: "Days of Activity",
    number: 316,
    percentage: 23,
    subtext: "days",
    text: "Compared to last month",
    direction: "up",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
    ],
  },
  {
    id: 3,
    icon: <BiUserCheck />,
    title: "users",
    number: 316,
    percentage: 23,
    text: "Compared to last month",
    direction: "down",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
    ],
  },
  {
    id: 4,
    icon: <BiGlobe />,
    title: "Web Activity",
    number: 316,
    percentage: 23,
    subtext: "Activities",
    text: "Compared to last month",
    direction: "up",
    data: [
      {
        name: "Page A",
        uv: 4000,
        pv: 2400,
        amt: 2400,
      },
      {
        name: "Page B",
        uv: 3000,
        pv: 1398,
        amt: 2210,
      },
      {
        name: "Page C",
        uv: 2000,
        pv: 9800,
        amt: 2290,
      },
    ],
  },
];

export const tableData = [
  {
    id: 1,
    online: true,
    name: "Annette Black",
    avatar: null,
    location: "Ottawa, Canada",
    org: "MSBM, Ottawa",
    device: "Windows",
    activity: "Google Chrome",
    timeUsage: "3 hours 12 minutes",
  },
  {
    id: 2,
    online: true,
    name: "Floyd Miles",
    avatar: null,
    location: "Lagos, Nigeria",
    org: "MSBM, Lagos",
    device: "Windows",
    activity: "Instagram",
    timeUsage: "2 hours 8 minutes",
  },
  {
    id: 3,
    online: false,
    name: "Ronald Richards",
    avatar: null,
    location: "Dubai, UAE",
    org: "MSBM, Dubai",
    device: "Mac",
    activity: "Microsoft Teams",
    timeUsage: "6 hours 45 minutes",
  },
  {
    id: 4,
    online: true,
    name: "Guy Hawkins",
    avatar: null,
    location: "London, UK",
    org: "MSBM, London",
    device: "Windows",
    activity: "Instagram",
    timeUsage: "1 hour 30 minutes",
  },
  {
    id: 5,
    online: false,
    name: "Jane Cooper",
    avatar: null,
    location: "Frankfurt, Germany",
    org: "MSBM, Frankfurt",
    device: "Mac",
    activity: "Google Chrome",
    timeUsage: "9 hours 10 minutes",
  },
  {
    id: 6,
    online: false,
    name: "Leslie Alexander",
    avatar: null,
    location: "Rome, Italy",
    org: "MSBM, Rome",
    device: "Windows",
    activity: "YouTube",
    timeUsage: "45 minutes",
  },
  {
    id: 7,
    online: false,
    name: "Annette Black",
    avatar: null,
    location: "Calgary, Canada",
    org: "MSBM, Calgary",
    device: "Linux",
    activity: "Opera Mini",
    timeUsage: "45 minutes",
  },
  {
    id: 8,
    online: true,
    name: "Floyd Miles",
    avatar: null,
    location: "Mumbai, India",
    org: "MSBM, Mumbai",
    device: "Mac",
    activity: "WhatsApp",
    timeUsage: "45 minutes",
  },
  {
    id: 9,
    online: false,
    name: "Cody Fisher",
    avatar: null,
    location: "Lagos, Nigeria",
    org: "MSBM, Lagos",
    device: "Windows",
    activity: "Microsoft Teams",
    timeUsage: "45 minutes",
  },
  {
    id: 10,
    online: true,
    name: "Dianne Russell",
    avatar: null,
    location: "London, UK",
    org: "MSBM, London",
    device: "Linux",
    activity: "YouTube",
    timeUsage: "45 minutes",
  },
];

export const APP_DATA = [
  {
    id: 1,
    app: "Google Chrome",
    users: 34,
    hours: "3 hours 12 minutes",
    date: "2024-06-26 15:33:49",
  },
  {
    id: 2,
    app: "YouTube",
    users: 12,
    hours: "2 hours 8 minutes",
    date: "2024-05-26 12:45:41",
  },
  {
    id: 3,
    app: "Microsoft Teams",
    users: 16,
    hours: "6 hours 45 minutes",
    date: "2024-05-21 16:28:21",
  },
  {
    id: 4,
    app: "WhatsApp",
    users: 49,
    hours: "1 hour 30 minutes",
    date: "2024-06-26 15:33:49",
  },
  {
    id: 5,
    app: "Opera Mini",
    users: 3,
    hours: "9 hours 10 minutes",
    date: "2024-05-21 16:28:21",
  },
  {
    id: 6,
    app: "Instagram",
    users: 22,
    hours: "45 minutes",
    date: "2024-05-26 12:45:41",
  },
];

export const WEB_DATA = [
  { id: 1, app: "Chrome", pct: 78, time: "5 hours 12 minutes" },
  { id: 2, app: "Gmail", pct: 61, time: "2 hours 24 minutes" },
  { id: 3, app: "Firefox", pct: 45, time: "40 minutes" },
  { id: 4, app: "Instagram", pct: 78, time: "5 hours 6 minutes" },
  { id: 5, app: "x.com", pct: 59, time: "1 hours 8 minutes" },
  { id: 6, app: "Facebook", pct: 61, time: "3 hours 1 minute" },
];
