import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "../components/common/Sidebar";
import Navbar from "../components/common/Navbar";

const poppins = {
  variable: "--font-poppins",
  fontFamily: "Poppins, sans-serif",
};

export const metadata: Metadata = {
  title: "Snaarp Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`}>
      <body className={"h-full w-full"}>
        <Sidebar />
        <Navbar />
        <section className="ml-0 md:ml-64 pt-14 md:pt-14 h-dvh overflow-auto bg-slate-50">
          <div className="max-w-9xl mx-auto p-3 md:p-4">{children}</div>
        </section>
      </body>
    </html>
  );
}
